### ISSUE TITLE
`clang` package broken

### ISSUE THREAD

**Issue by shirok1** [batocera-linux/buildroot#488]
It seems that you have bumped `clang` to 14:

https://github.com/batocera-linux/buildroot/blob/125f6c585fd4f413c96595f31515153d5b7ec5cd/package/clang/clang.mk#L9

But your hash is not updated:

https://github.com/batocera-linux/buildroot/blob/125f6c585fd4f413c96595f31515153d5b7ec5cd/package/clang/clang.hash#L2

What's more, LLVM 14 distributes CMake modules separately, which means `cmake-**.tar.xz` should be downloaded and extracted to `cmake` folder, or it won't configure:

```console
CMake Error at cmake/modules/CMakeLists.txt:1 (include):
  include could not find requested file:
    ExtendPath
CMake Error at cmake/modules/CMakeLists.txt:3 (include):
  include could not find requested file:
    FindPrefixFromConfig
CMake Error at cmake/modules/CMakeLists.txt:42 (find_prefix_from_config):
  Unknown CMake command "find_prefix_from_config".
```

**Comment by dmanlfc** [comment]
yeah we don't use clang... yet... buildroot is WAY behind on all this stuff
