### ISSUE TITLE
[RK3588] - Video Playback not hardware accelerated through the built-in Kodi

### ISSUE THREAD

**Issue by mo123** [batocera-linux/buildroot#575]
It can be fixed by using the following
FFMPEG for RK3588 devices only.
[https://github.com/JeffyCN/FFmpeg/tree/4.4](url)

Also needs mpp package
[https://github.com/rockchip-linux/mpp](url)

and Kodi package needs to be build with
BR2_PACKAGE_KODI20_RENDER_SYSTEM_GLES

**Comment by dmanlfc** [comment]
thanks @mo123 

this is not the place to post such things but it is noted. have you tried it?
