### ISSUE TITLE
Feature request: add upower

### ISSUE THREAD

**Issue by git-developer** [batocera-linux/buildroot#791]
This is a feature request to add `upower` to batocera.

#### Context
I'm the maintainer of [batocera-extra](https://github.com/git-developer/batocera-extra), an addon to batocera for motion and touch support. Motion is provided by running a cemuhook server that reads motion data from game controllers and exports that data to emulators. There are different cemuhook servers available, and batocera-extra integrates them.

#### Problem
Some of the cemuhook servers require `upower` which is not part of batocera. `upower` and its [dependencies](https://github.com/git-developer/batocera-extra/blob/3969ec521a6c9f438e9d2c7e0df3fefbc1d9ee40/bin/upowerd-start#L7) are downloaded from the Arch linux package repository. This works only for the `amd64` platform because Arch does not support other platforms.

#### Feature Request
[batocera-extra #6](https://github.com/git-developer/batocera-extra/issues/6) is a feature request for support of the `aarch64` platform. Nicolas once [commented](https://github.com/git-developer/batocera-extra/issues/1#issuecomment-1495394134)

> BR2_PACKAGE_UPOWER is just a package to enable as a dependancy where needed

I'd like to ask how this can be done. Once `upower` is available, batocera-extra can be made available on other platforms, and download of libraries from Arch can be omitted.

I'm not sure if this request belongs to the buildroot or the batocera-linux repo, so please advise if it should be moved.

**Comment by nadenislamarre** [comment]
https://github.com/batocera-linux/batocera.linux/pull/11558
